# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/x8qyfphi04lhj621if89f8il33v9dnny-cmake-3.30.5/bin/cmake

# The command to remove a file.
RM = /nix/store/x8qyfphi04lhj621if89f8il33v9dnny-cmake-3.30.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/fbs/private/codeforces/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/fbs/private/codeforces/cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/x8qyfphi04lhj621if89f8il33v9dnny-cmake-3.30.5/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/x8qyfphi04lhj621if89f8il33v9dnny-cmake-3.30.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fbs/private/codeforces/cpp/CMakeFiles /Users/fbs/private/codeforces/cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fbs/private/codeforces/cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named angry_monk

# Build rule for target.
angry_monk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 angry_monk
.PHONY : angry_monk

# fast build rule for target.
angry_monk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angry_monk.dir/build.make CMakeFiles/angry_monk.dir/build
.PHONY : angry_monk/fast

#=============================================================================
# Target rules for targets named watermelon

# Build rule for target.
watermelon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 watermelon
.PHONY : watermelon

# fast build rule for target.
watermelon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/watermelon.dir/build.make CMakeFiles/watermelon.dir/build
.PHONY : watermelon/fast

#=============================================================================
# Target rules for targets named books

# Build rule for target.
books: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 books
.PHONY : books

# fast build rule for target.
books/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/books.dir/build.make CMakeFiles/books.dir/build
.PHONY : books/fast

#=============================================================================
# Target rules for targets named two_buttons

# Build rule for target.
two_buttons: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 two_buttons
.PHONY : two_buttons

# fast build rule for target.
two_buttons/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/two_buttons.dir/build.make CMakeFiles/two_buttons.dir/build
.PHONY : two_buttons/fast

angry_monk.o: angry_monk.cpp.o
.PHONY : angry_monk.o

# target to build an object file
angry_monk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angry_monk.dir/build.make CMakeFiles/angry_monk.dir/angry_monk.cpp.o
.PHONY : angry_monk.cpp.o

angry_monk.i: angry_monk.cpp.i
.PHONY : angry_monk.i

# target to preprocess a source file
angry_monk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angry_monk.dir/build.make CMakeFiles/angry_monk.dir/angry_monk.cpp.i
.PHONY : angry_monk.cpp.i

angry_monk.s: angry_monk.cpp.s
.PHONY : angry_monk.s

# target to generate assembly for a file
angry_monk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/angry_monk.dir/build.make CMakeFiles/angry_monk.dir/angry_monk.cpp.s
.PHONY : angry_monk.cpp.s

books.o: books.cpp.o
.PHONY : books.o

# target to build an object file
books.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/books.dir/build.make CMakeFiles/books.dir/books.cpp.o
.PHONY : books.cpp.o

books.i: books.cpp.i
.PHONY : books.i

# target to preprocess a source file
books.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/books.dir/build.make CMakeFiles/books.dir/books.cpp.i
.PHONY : books.cpp.i

books.s: books.cpp.s
.PHONY : books.s

# target to generate assembly for a file
books.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/books.dir/build.make CMakeFiles/books.dir/books.cpp.s
.PHONY : books.cpp.s

two_buttons.o: two_buttons.cpp.o
.PHONY : two_buttons.o

# target to build an object file
two_buttons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/two_buttons.dir/build.make CMakeFiles/two_buttons.dir/two_buttons.cpp.o
.PHONY : two_buttons.cpp.o

two_buttons.i: two_buttons.cpp.i
.PHONY : two_buttons.i

# target to preprocess a source file
two_buttons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/two_buttons.dir/build.make CMakeFiles/two_buttons.dir/two_buttons.cpp.i
.PHONY : two_buttons.cpp.i

two_buttons.s: two_buttons.cpp.s
.PHONY : two_buttons.s

# target to generate assembly for a file
two_buttons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/two_buttons.dir/build.make CMakeFiles/two_buttons.dir/two_buttons.cpp.s
.PHONY : two_buttons.cpp.s

watermelon.o: watermelon.cpp.o
.PHONY : watermelon.o

# target to build an object file
watermelon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/watermelon.dir/build.make CMakeFiles/watermelon.dir/watermelon.cpp.o
.PHONY : watermelon.cpp.o

watermelon.i: watermelon.cpp.i
.PHONY : watermelon.i

# target to preprocess a source file
watermelon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/watermelon.dir/build.make CMakeFiles/watermelon.dir/watermelon.cpp.i
.PHONY : watermelon.cpp.i

watermelon.s: watermelon.cpp.s
.PHONY : watermelon.s

# target to generate assembly for a file
watermelon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/watermelon.dir/build.make CMakeFiles/watermelon.dir/watermelon.cpp.s
.PHONY : watermelon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... angry_monk"
	@echo "... books"
	@echo "... two_buttons"
	@echo "... watermelon"
	@echo "... angry_monk.o"
	@echo "... angry_monk.i"
	@echo "... angry_monk.s"
	@echo "... books.o"
	@echo "... books.i"
	@echo "... books.s"
	@echo "... two_buttons.o"
	@echo "... two_buttons.i"
	@echo "... two_buttons.s"
	@echo "... watermelon.o"
	@echo "... watermelon.i"
	@echo "... watermelon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

